#logging:
#    level:
#        ROOT: #logback.loglevel#
#        co.riro.stripedebitcardservice: #logback.loglevel#

server:
    port: 8081

grpc:
    port: 6585

app:
    name: "go-base-service"
    version: "1.0.0"
    secret_key: "prod_secret_key"
    debug: false

auth:
    domain: "dev-dev53al0gd7odyq5.us.auth0.com"
    audience: "https://auth-dev.finster.ai"
    algorithms: ["RS256"]

persistence:
    sql:
        uri: "DEVELOPMENT_DB_URL"
        pool_size: 20
        version: 1.1.4
    mongodb:
        uri: "mongodb+srv://finster-dev:3tLRNLbel7DCZCal@finster-dev.gixif.mongodb.net/?retryWrites=true&w=majority&appName=finster-dev"
        name: "go_base_service"
    redis:
        host: "redis-12997.c259.us-central1-2.gce.redns.redis-cloud.com"
        port: 12997
        password: 'dJ6czkdTtsTqWreLP4gRvT3VYydgIjaa'
    #    kafka:
    #        bootstrap-servers: 127.0.0.1:9092
    #        consumer:
    #            enabled: true
    #            type: "string"
    #            group-id: "stripe-debit-card-group"
    pubsub:
        project_id: "finster-dev"
        topic_id: "test-queue-dev-emmanuel"
        subscription_id: "test-queue-dev-emmanuel-sub"
